spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    username:
#    password:
#    url:
#    hikari:
#      maximum-pool-size: 10
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;MODE=MYSQL
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
#    database: mysql
    defer-datasource-initialization: true
    open-in-view: false # ???? ?? ??? ??? ????? ???? ??
#    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create # create-drop, update, validate, none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        use-sql-comments: true
        default-batch-fetch-size: 500
  servlet:
    multipart:
      max-request-size: 300MB
      max-file-size: 300MB